Update cd

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,10 +1,8 @@
 name: Deploy to cloud run
 
 on:
-  push:
-    branches:
-      - main
-  workflow_dispatch:
+  pull_request:
+    types: [closed]
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
@@ -13,28 +11,41 @@ concurrency:
 jobs:
   deploy:
     permissions:
-       contents: "write"
-       id-token: "write"
+      contents: "write"
+      id-token: "write"
     name: Upload image and deploy cloud run
     runs-on: ubuntu-latest
+    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
     steps:
-      - name: Install GitVersion
-        uses: gittools/actions/gitversion/setup@v1.1.1
-        with:
-          versionSpec: '5.x'
-
       - name: Checkout code
         uses: actions/checkout@v4
         with:
           persist-credentials: false
           fetch-depth: 0
-      
+
       - name: Determine Version
         id: gitversion
-        uses: gittools/actions/gitversion/execute@v1.1.1
-        with:
-          useConfigFile: true
-          configFilePath: GitVersion.yml
+        run: |
+          BRANCH_NAME="${{ github.head_ref }}"
+          echo "Branch Name: $BRANCH_NAME"
+          VERSION_REGEX="([0-9]+.[0-9]+.[0-9]+)"
+          if [[ $BRANCH_NAME =~ $VERSION_REGEX ]]
+          then
+            VERSION="${BASH_REMATCH[1]}"
+            echo "Version: $VERSION"
+            VER_CR="${VERSION//./-}"
+            echo "Version_CR: $VER_CR"
+            echo "fullSemVer=$VERSION" >> "$GITHUB_OUTPUT"
+            echo "verCR=$VER_CR" >> "$GITHUB_OUTPUT"
+          else
+            echo "Error: No version found in branch name"
+            exit 1
+          fi
+
+      - name: Create release
+        run: gh release create v${{ steps.gitversion.outputs.fullSemVer }} -F CHANGELOG.md
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Authenticate to Google Cloud
         id: auth
@@ -54,17 +65,14 @@ jobs:
       - name: Build and upload image to Artifact Registry
         run: |
           docker build -f Dockerfile \
+            -t europe-west1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/codegen/analytical-assistant:latest \
             -t europe-west1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/codegen/analytical-assistant:v${{ steps.gitversion.outputs.fullSemVer }} . \
             --build-arg GAR_ACCESS_TOKEN=${{ steps.auth.outputs.access_token }}
-          docker push europe-west1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/codegen/analytical-assistant:v${{ steps.gitversion.outputs.fullSemVer }}
-      
+          docker push -a europe-west1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/codegen/analytical-assistant
+
       - name: Deploy cloud run
         id: deploy
         run: |
           gcloud run services update segment --region europe-west1 \
-            --image europe-west1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/codegen/analytical-assistant:v${{ steps.gitversion.outputs.fullSemVer }}
-
-      - name: Create release
-        run: gh release create v${{ steps.gitversion.outputs.fullSemVer }}
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+            --image europe-west1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/codegen/analytical-assistant:latest \
+            --tag v${{ steps.gitversion.outputs.verCR }}
